openapi: 3.0.0
info:
  title: API de Carritos
  description: API para administrar carritos de compras.
  version: 1.0.0

paths:
  /api/carts:
    get:
      summary: Obtiene todos los carritos
      tags:
        - Carts
      responses:
        '200':
          description: Se obtuvieron los carritos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"
        '500':
          description: Error del servidor. Usualmente generando la query o falla la conexión a la DB
    post:
      summary: Creación de Nuevo Carrito
      tags:
        - Carts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCart"
      responses:
        '201':
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '500':
          description: Algunos de los parámetros requeridos están ausentes o son incorrectos para completar la petición
  '/api/carts/{cid}':
    get:
      summary: Obtiene un carrito por ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito que se busca
          schema:
            type: string
      responses:
        '200':
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '500':
          description: Algunos de los parámetros requeridos están ausentes o son incorrectos para completar la petición.
    put:
      summary: Actualiza un carrito por ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito que se busca
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCart"
      responses:
        '200':
          description: Carrito modificado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '500':
          description: Algunos de los parámetros requeridos están ausentes o son incorrectos para completar la petición.
    delete:
      summary: Elimina un carrito por ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito que se busca eliminar
          schema:
            type: string
      responses:
        '200':
          description: Carrito eliminado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '500':
          description: Algunos de los parámetros requeridos están ausentes o son incorrectos para completar la petición.
  '/api/carts/{cid}/products/{pid}':
    put:
      summary: Actualiza la cantidad de un producto en un carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductQuantity"
      responses:
        '200':
          description: Cantidad de producto en el carrito actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '500':
          description: Algunos de los parámetros requeridos están ausentes o son incorrectos para completar la petición.
    delete:
      summary: Elimina un producto de un carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado del carrito exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito
        products:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                description: ID del producto
              name:
                type: string
                description: Nombre del producto
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
      example:
        _id: "1"
        products:
          - _id: "101"
            name: "Producto 1"
            quantity: 3
    NewCart:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                description: ID del producto
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
      example:
        products:
          - _id: "101"
            quantity: 2
    UpdateCart:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                description: ID del producto
              quantity:
                type: integer
                description: Nueva cantidad del producto en el carrito
      example:
        products:
          - _id: "101"
            quantity: 3
    UpdateProductQuantity:
      type: object
      properties:
        quantity:
          type: integer
          description: Nueva cantidad del producto en el carrito
      example:
        quantity: 5
